### ISSUE TITLE
No matching models: "face-reidentification-retail-0095"

### ISSUE THREAD

**Issue by MauryaShraddha** [opencv/gst-video-analytics#104]
Hello,

I recently updated my openvino image in the docker from 2020.3 to 2020.4.287.
I am trying to download the models using the download_models.sh file in the samples folder as follows: 
`root@default:/opt/intel/openvino_2020.4.287/data_processing/dl_streamer/samples# ./download_models.sh`
 But I am getting the following statement and the models are not being downloaded:
`Downloading models to folder /root/intel/dl_streamer/models` 
`No matching models: "face-reidentification-retail-0095"`

Can you please help me to download the models? @adranit @nnshah1

Thank you

**Comment by easychizy** [comment]
Hi @MauryaShraddha ,

This is a known issue. The download_models.sh script downloads the intel supported models from [Intel Open Model Zoo](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel).

Because of the updated company policy, [Open Model Zoo has remove this model](https://github.com/openvinotoolkit/open_model_zoo/commit/97b3ff7fcf88fa472d868e5323aef8048907aa06#diff-fe8b8cbb4c0b48b0a2ed61c70f832406).

DL Streamer doesn't use this model anymore and we will fix it in next release. You can remove this model from models.lst, the script will work.

Mark

**Comment by MauryaShraddha** [comment]
It worked!

Thank you @easychizy
