### ISSUE TITLE
Confusing "Run Samples" directions when using docker container

### ISSUE THREAD

**Issue by js333031** [opencv/gst-video-analytics#25]
I built the container, ran the command in "Run container:" step and got into the container's shell prompt.

The directions say to go to "Run Samples" section. The steps there seem to be for the host machine, not the container. 

For example, in the container, setupvars.sh is found in ./opt/intel/dldt/inference-engine/external/opencv_4.1.1_ubuntu16/

Additionally, using the docker run command in "Run container" section, the container doesn't have a ~/gva directory as shown in "Run Samples" command.

root@clftower:/# cd ~/gva
bash: cd: /root/gva: No such file or directory
root@clftower:/#

**Comment by synchronizing** [comment]
Check out #68. Had the same issue as well, but some folks gave some worthy insights.

**Comment by easychizy** [comment]
Hi @js333031,

I think the issues are well discussed at #68 and could we close this issue?

Basically, the document you are referenced is old and was removed since our new release. We have 2 paths for Docker support:
[VA serving](https://github.com/intel/video-analytics-serving)
[OpenVINO Docker image](https://hub.docker.com/r/openvino/ubuntu18_data_dev)

Let me know if you have more questions, we will wait for couple days and close it if no more comments.

Mark
