### ISSUE TITLE
vainfo errors inspite of reboot

### ISSUE THREAD

**Issue by subashp** [opencv/gst-video-analytics#30]
$ vainfo 
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva error: /opt/intel/mediasdk/lib64/iHD_drv_video.so has no function __vaDriverInit_0_32
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

Due to unavoidable reasons, I am using Ubuntu 16.04 instead of 18.04. Would this cause this driver error?

**Comment by brmarkus** [comment]
Can you provide a bit more information about your environment, please?

How have you installed libva? Have you installed it via "gst-video-analytics/scripts/build_install_libva.sh" from this repo? The version "VA-API version 0.39.0" looks wrong. Looks like you have a legacy environment.

How have you installed MediaSDK? Have you installed it via "gst-video-analytics/scripts/install_dependencies.sh"?

Can you call the following command, please?

$> strings /opt/intel/mediasdk/lib64/iHD_drv_video.so | grep vaDriverInit

**Comment by Andruxin52rus** [comment]
Hi @subashp !
First of all, please note, that VA-API and iHD driver are needed only if you want to use gstreamer vaapi elements. It means that the issue you reported doesn't block you from, for instance, running pipelines with software decode. Just go thru the rest of GSG and try to run samples.
Second, if you're really sure you want to test vaapi-based pipelines, please follow @brmarkus advices. I would also suggest you to install Media SDK 2018Q2.2 (https://github.com/Intel-Media-SDK/MediaSDK/releases/download/MediaSDK-2018-Q2.2/MediaStack.tar.gz) instead of 19.1.0 version (this may be related to your Ubuntu 16 installation)
