### ISSUE TITLE
openvino instance sharing

### ISSUE THREAD

**Issue by sayanmutd** [opencv/gst-video-analytics#35]
Can anyone please explain what it means to share openvino model instance between various instances of pipeline?

**Comment by brmarkus** [comment]
Are you referring to a section/feature in the documentation, if yes, which?

If the gstreamer pipeline consists of multiple gst-video-analytics plugins (e.g. from "https://github.com/opencv/gst-video-analytics/wiki/Getting-Started-Guide-%5BR3%5D#introduction": "gst-launch-1.0 filesrc location=cut.mp4 ! decodebin ! videoconvert ! gvadetect model=face-detection-adas-0001.xml ! gvaclassify model=emotions-recognition-retail-0003.xml model-proc=emotions-recognition-retail-0003.json ! gvawatermark ! ximagesink sync=false", i.e. "gvadetect" and "gvaclassify" and "gvawatermark") then all gva plugins would share the same "OpenVINO instance" (e.g. the same inference-engine instance) instead of each plugin allocating&instantiating its own instance.

**Comment by sayanmutd** [comment]
Suppose if we want to use multiple pipeline which has different sources, then can we use the same openvino instance?

**Comment by umed** [comment]
Hi @sayanmutd ,

> Suppose if we want to use multiple pipeline which has different sources, then can we use the same openvino instance?

Exactly! With the only limitation, all pipelines must be launched by the same instance of gst-launch or call of `gst_parse_launch`. Here is [example](https://github.com/opencv/gst-video-analytics/blob/master/samples/shell/face_detection_multichannel.sh)

**Comment by umed** [comment]
There are no comments in 7 days. So, I'm closing it.

Feel free to reopen.
