### ISSUE TITLE
 GST_PLUGIN_PATH env variable

### ISSUE THREAD

**Issue by js07920** [opencv/gst-video-analytics#6]
Should $GST_PLUGIN_PATH already exist. The "build on host machine" directions specify that the env variable should be set but the command implies the variable exists already. In my case, by default, the env variable is not set.

export GST_PLUGIN_PATH=$GST_PLUGIN_PATH:~/gst-video-analytics/build/intel64/Release/lib

**Comment by SDxKeeper** [comment]
It's just regular linux way to append into path like variables. Do you see some problems if it will be set to "<empty>:build_path"?

**Comment by Andruxin52rus** [comment]
Hi @js07920 ! We don't use `export GST_PLUGIN_PATH=~/gst-video-analytics/build/intel64/Release/lib`, because it is not user-friendly to replace some general purpose variables with our own values. `GST_PLUGIN_PATH` is used by GStreamer to find plugins and we just append our path to the end, so if you had some paths already set there, our installation won't ruin your environment
